---
- name: Check presence of Google Chrome
  command: rpm -q google-chrome-stable
  register: google_chrome_rpm_check
  check_mode: no
- name: Install Google Chrome
  package:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
  become: true
  when: google_chrome_rpm_check.rc == 1
