---
- hosts: localhost
  become_user: root
  roles:
    - additional-packages
    - bash
    - datovka
    - devel
    - devel-ui
    #- disable-acpi-wakeups
    - docker
    - emacs
    - fedora-codecs
    #- fedora-packaging
    #- fix-pulseaudio-popping-sound
    #- google-chrome
    - spacemacs
    - spotify
    - thinkpad-battery-longlife
    - user-groups
    - vagrant
    - vim
    - zsh