---
- name: Install packages
  package:
    name:
      - xss-lock
      - i3lock
    state: present
  become: yes
- name: Install service
  vars:
    locker_command: i3lock -n -e -f -c 000000
  template:
    src: "xss-lock.service"
    dest: "{{ ansible_user_dir }}/.config/systemd/user/xss-lock.service"
    backup: yes
  register: service_file
- name: Enable and (re)start the service
  systemd:
    name: "xss-lock.service"
    daemon_reload: yes
    user: yes
    enabled: yes
    state: "{{ 're' if service_file.changed else '' }}started"
