---
- name: Install xscreensaver package
  package:
    name: xscreensaver
    state: present
  become: yes
- name: Install xscreensaver service
  copy:
    src: xscreensaver.service
    dest: "{{ ansible_user_dir }}/.config/systemd/user/xscreensaver.service"
    backup: yes
  register: xscreensaver_service_file
- name: Enable and start the xscreensaver service
  systemd:
    name: xscreensaver.service
    daemon_reload: yes
    user: yes
    enabled: yes
    state: "{{ 're' if xscreensaver_service_file.changed else '' }}started"
- name: Enable sleep hooks
  include_tasks: sleep-hook.yml
  with_items:
    - { name: before, option: Before }
    - { name: after, option: After }
