---
- set_fact:
    name: "{{ item.name }}"
    option: "{{ item.option }}"
- set_fact:
    service_name: "xscreensaver-{{ name }}-sleep@.service"
- name: place a service file
  template:
    src: xscreensaver-sleep.service.j2
    dest: "/etc/systemd/system/{{ service_name }}"
    backup: yes
  become: yes
- name: enable the sleep hook
  systemd:
    name: "xscreensaver-{{ name }}-sleep@{{ ansible_user_id }}.service"
    daemon_reload: yes
    enabled: yes
  become: yes
