---
- name: add RPM Fusion repositories
  yum_repository:
    name: "rpmfusion-{{ item }}"
    description: "RPM Fusion {{ item }} repository"
    baseurl: "https://download1.rpmfusion.org/{{ item }}/fedora/releases/$releasever/Everything/$basearch/os/"
    enabled: "{{ item == 'free' }}"
    gpgcheck: no
  with_items:
    - free
    - nonfree
  become: yes
- name: install codecs and VLC
  package:
    name:
      - gstreamer1-plugins-base
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-bad-freeworld
      - ffmpeg
      - gstreamer-ffmpeg
      - vlc
    state: present
  become: yes
