---
- set_fact:
    svc_name: portainer.service
- name: Install service file
  copy:
    src: "{{ svc_name }}"
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{ svc_name }}"
  register: svc_file
- name: Ensure started service
  systemd:
    name: "{{ svc_name }}"
    user: yes
    daemon_reload: yes
    enabled: yes
    state: "{{ 're' if svc_file.changed or svc_file.changed else '' }}started"
