---
- name: install packages
  package:
    name: redshift
    state: present
  become: yes
- name: ensure service directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory
    recurse: yes
- name: install service
  copy:
    src: redshift.service
    dest: "{{ ansible_user_dir }}/.config/systemd/user/redshift.service"
    backup: yes
  register: redshift_service_file
- name: enable and start service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: redshift.service
    state: "{{ 're' if redshift_service_file.changed else '' }}started"
    no_block: yes
    user: yes
