---
- set_fact:
    dump_cmd: "dconf dump /com/gexperts/Tilix/"
    load_cmd: "dconf load /com/gexperts/Tilix/"
    cfg_file: "config"
- name: install packages
  package:
    name:
      - tilix
      - adobe-source-code-pro-fonts
    state: present
  become: yes
- name: diff the configs
  shell:
    cmd: |
      diff -u <( {{ dump_cmd }} ) <(cat <<"EOFNOTEVERFOUND"
      {{ lookup('file', cfg_file) }}
      EOFNOTEVERFOUND
      )
  args:
    executable: /bin/bash
  register: diff
  changed_when: diff.rc == 1
  failed_when: (diff.rc == 2) or diff.stderr
  check_mode: no
- name: show changes
  debug: var=diff.stdout_lines
  when: diff.changed
- name: apply new configuration
  block:
    - name: create temp file for new config
      tempfile:
        state: file
      register: tmp
    - name: copy new config dump to temporary location
      copy:
        src: config
        dest: "{{ tmp.path }}"
    - name: update configuration
      shell: "{{ load_cmd }} < {{ tmp.path | quote }}"
    - name: remove temp file
      file:
        name: "{{ tmp.path }}"
        state: absent
  when: diff.changed and not ansible_check_mode
