---
- name: Ensure system Docker is absent
  package:
    name: docker
    state: absent
  become: yes
- name: Add Docker-CE repo
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    backup: yes
  become: yes
- name: Install Docker CE packages
  package:
    name: docker-ce
    state: present
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
- name: Ensure docker group exists
  group:
    name: docker
  become: yes
- name: Add the user to docker group
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker
  become: yes
