---
- name: Have my COPR repo
  command: dnf -y copr enable mhonek/sway
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:mhonek:sway.repo
    warn: false
  become: yes

- name: Install packages
  package:
    name:
      - sway
      - swaybg
      - swayidle
      - swaylock
      - mako
    state: present
  become: yes
