---
- name: Have my COPR repo
  command: dnf -y copr enable mhonek/sway
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:mhonek:sway.repo
    warn: false
  become: yes

- name: Install packages
  package:
    name:
      - bemenu
      - grim
      - kanshi
      - mako
      - slurp
      - sway
      - swaybg
      - swayidle
      - swaylock
      - xdg-desktop-portal-wlr
    state: present
  become: yes

- include: firefox-on-wayland.yml
