---
- name: have repo
  command: "yum copr enable -y mhonek/playerctl"
  args:
    creates: /etc/yum.repos.d/_copr_mhonek-playerctl.repo
  become: yes
- name: install playerctl
  package:
    name: playerctl
    state: present
  become: yes
