---
- set_fact:
    user: acrisci
    prog: playerctl
    base: "{{ ansible_user_dir }}/opt"
- set_fact:
    clone: "{{ base }}/{{ prog }}"
- name: clone repo
  git:
    repo: "https://github.com/{{ user }}/{{ prog }}.git"
    dest: "{{ clone }}"
    force: yes
- name: install build deps
  package:
    name:
      - redhat-rpm-config
      - gobject-introspection-devel
      - gtk-doc
      - libtool
    state: present
  become: yes
- name: build
  shell: |
    ./autogen.sh && make
  args:
    chdir: "{{ clone }}"
- name: symlink to ~/bin
  file:
    src: "{{ clone }}/{{ prog }}/{{ prog }}"
    dest: "{{ ansible_user_dir }}/bin/{{ prog }}"
    state: link
