---
- name: Install package
  package:
    name: dunst
    state: present
  become: yes
- name: Have config dir
  file:
    path: "{{ ansible_user_dir }}/.config/dunst"
    state: directory
- name: Place config file
  copy:
    src: dunstrc
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    backup: yes
  register: dunst_config_file
- name: Check I will run
  command: grep -q "^exec.*dunst" "{{ i3conf_path }}"

- include_tasks: track-i3lock.yml
