---
- name: Install package
  package:
    name: dunst
    state: present
  become: yes
- name: Have config dir
  file:
    path: "{{ ansible_user_dir }}/.config/dunst"
    state: directory
- name: Place config file
  copy:
    src: dunstrc
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    backup: yes
  register: dunst_config_file
- name: Place logging script
  copy:
    src: dunst-log.sh
    dest: "{{ ansible_user_dir }}/bin/dunst-log.sh"
    backup: yes
- name: Enable and start the service
  systemd:
    name: dunst.service
    daemon_reload: yes
    user: yes
    enabled: yes
    state: started

- include_tasks: track-i3lock.yml
