---
- name: Install packages
  package:
    name:
      - i3
      - jq
      - py3status
      - dunst
      - i3lock
      - xss-lock
      - xautolock
      - redshift-gtk
    state: present
  become: yes

# configs
- name: ensure .config/i3 dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/i3"
    state: directory
- name: copy i3 config
  copy:
    src: i3.config
    dest: "{{ ansible_user_dir }}/.config/i3/config"
- name: ensure .config/i3status dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/i3status"
    state: directory
- name: copy py3status config
  copy:
    src: py3status.config
    dest: "{{ ansible_user_dir }}/.config/i3status/config"

- name: Set up xbacklight
  import_tasks: backlight.yml

# adjust power management behaviour
- name: set behaviour on lid closing and power kye pressing
  lineinfile:
    dest: "/etc/systemd/logind.conf"
    insertafter: "^\\[Login\\]$"
    regexp: "^{{ item.attr }}=.*$"
    line: "{{ item.attr }}={{ item.value }}"
    backup: yes
  with_items:
    - { attr: HandleLidSwitch, value: lock }
    - { attr: HandlePowerKey, value: suspend }
  become: yes
  register: logind_conf_file
- name: restart systemd-logind
  when: logind_conf_file.changed
  systemd:
    name: systemd-logind
    state: restarted
  become: yes
