---
- name: Install packages
  package:
    name:
      - i3
      - jq
      - py3status
      - redshift-gtk
    state: present
  become: yes

- set_fact:
    i3conf_dir: "{{ ansible_user_dir }}/.config/i3"
- set_fact:
    i3conf_path: "{{ i3conf_dir }}/config"
- name: ensure .config/i3 dir exists
  file:
    path: "{{ i3conf_dir }}"
    state: directory
- name: copy i3 config
  copy:
    src: i3.config
    dest: "{{ i3conf_path }}"
    mode: 0640

- name: ensure .config/i3status dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/i3status"
    state: directory
- name: copy py3status config
  copy:
    src: py3status.config
    dest: "{{ ansible_user_dir }}/.config/i3status/config"
    mode: 0640

- name: Set up xbacklight
  import_tasks: backlight.yml

- name: Adjust power buttons behaviour
  import_tasks: power-buttons.yml

- name: Set up dunst
  import_tasks: dunst.yml

- name: Set up i3lock
  import_tasks: i3lock.yml

- name: Install xinit.sh
  copy:
    src: xinit.sh
    dest: "{{ ansible_user_dir }}/bin/xinit.sh"
    mode: 0770
    backup: yes

- name: Set up .Xresources
  copy:
    src: Xresources
    dest: "{{ ansible_user_dir }}/.Xresources"
    mode: 0660
    backup: yes
  register: xresources_file
- name: Reload Xresources
  command: xrdb "{{ ansible_user_dir }}/.Xresources"
  check_mode: no
  when: xresources_file.changed
