---
- set_fact:
    prog: arandr-autoconfig
    base: "{{ ansible_user_dir }}/opt"
- set_fact:
    clone: "{{ base }}/{{ prog }}"
- name: clone repo
  git:
    repo: "https://github.com/kenoh/{{ prog }}.git"
    dest: "{{ clone }}"
    force: yes
- name: install requirements
  pip:
    requirements: "{{ clone }}/requirements.txt"
    extra_args: --user
    executable: pip3
- name: install service
  copy:
    src: "{{ prog }}.service"
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{ prog }}.service"
    backup: yes
  register: service_file
- name: Enable and start the service
  systemd:
    name: "{{ prog }}.service"
    daemon_reload: yes
    user: yes
    enabled: yes
    state: "{{ 're' if service_file.changed else '' }}started"
